//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartschoolWSDL
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://bazandpoort.smartschool.be/Webservices/V3", ConfigurationName="SmartschoolWSDL.V3Port")]
    public interface V3Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserAsync(
                    string accesscode, 
                    string internnumber, 
                    string username, 
                    string passwd1, 
                    string passwd2, 
                    string passwd3, 
                    string name, 
                    string surname, 
                    string extranames, 
                    string initials, 
                    string sex, 
                    string birthday, 
                    string birthplace, 
                    string birthcountry, 
                    string address, 
                    string postalcode, 
                    string location, 
                    string country, 
                    string email, 
                    string mobilephone, 
                    string homephone, 
                    string fax, 
                    string prn, 
                    string stamboeknummer, 
                    string basisrol, 
                    string untis);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveClassAsync(string accesscode, string name, string desc, string code, string parent, string untis, string instituteNumber, string adminNumber, string schoolYearDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveGroupAsync(string accesscode, string name, string desc, string code, string parent, string untis);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAllAccounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getAllAccountsAsync(string accesscode, string code, string recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAllAccountsExtended", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getAllAccountsExtendedAsync(string accesscode, string code, string recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAllGroupsAndClasses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getAllGroupsAndClassesAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#addCourse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> addCourseAsync(string accesscode, string coursename, string coursedesc, int visibility);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#addCourseTeacher", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> addCourseTeacherAsync(string accesscode, string coursename, string coursedesc, string internnummer, string userlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#addCourseStudents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> addCourseStudentsAsync(string accesscode, string coursename, string coursedesc, string groupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getCourses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCoursesAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#delUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> delUserAsync(string accesscode, string userIdentifier, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveUserParameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserParameterAsync(string accesscode, string userIdentifier, string paramName, string paramValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getClassList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getClassListAsync(object accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getClassListJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getClassListJsonAsync(object accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveClassList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveClassListAsync(string accesscode, string serializedList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveClassListJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveClassListJsonAsync(string accesscode, string jsonList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#delClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> delClassAsync(string accesscode, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveUserToClasses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserToClassesAsync(string accesscode, string userIdentifier, string csvList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#removeUserFromGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> removeUserFromGroupAsync(string accesscode, string userIdentifier, string @class, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#clearGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> clearGroupAsync(string accesscode, string group, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveUserToClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserToClassAsync(string accesscode, string userIdentifier, string @class, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveUserToClassesAndGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserToClassesAndGroupsAsync(string accesscode, string userIdentifier, string csvList, int keepOld);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#setAccountStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> setAccountStatusAsync(string accesscode, string userIdentifier, object accountStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#setAccountPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> setAccountPhotoAsync(string accesscode, string userIdentifier, string photo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAccountPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAccountPhotoAsync(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#replaceInum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> replaceInumAsync(string accesscode, string oldInum, string newInum);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#forcePasswordReset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> forcePasswordResetAsync(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#savePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> savePasswordAsync(string accesscode, string userIdentifier, string password, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#sendMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> sendMsgAsync(string accesscode, string userIdentifier, string title, string body, string senderIdentifier, object attachments, int coaccount, bool copyToLVS);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getSkoreClassTeacherCourseRelat" +
            "ion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getSkoreClassTeacherCourseRelationAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#unregisterStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> unregisterStudentAsync(string accesscode, string userIdentifier, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getClassTeachers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getClassTeachersAsync(string accesscode, bool getAllOwners);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAbsentsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAbsentsWithInternalNumberByD" +
            "ate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsWithInternalNumberByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAbsentsWithUsernameByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsWithUsernameByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAbsentsByDateAndGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsByDateAndGroupAsync(string accesscode, string date, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAbsentsWithAliasByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsWithAliasByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getAbsents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsAsync(string accesscode, string userIdentifier, string schoolYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserDetailsAsync(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getUserDetailsByNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserDetailsByNumberAsync(string accesscode, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getUserDetailsByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserDetailsByUsernameAsync(string accesscode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getUserOfficialClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserOfficialClassAsync(string accesscode, string userIdentifier, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveSignature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> saveSignatureAsync(string accesscode, string userIdentifier, int accountType, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getStudentCareer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getStudentCareerAsync(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#deactivateTwoFactorAuthenticati" +
            "on", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> deactivateTwoFactorAuthenticationAsync(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://bazandpoort.smartschool.be/Webservices/V3#returnErrorCodes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task returnErrorCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#returnCsvErrorCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> returnCsvErrorCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#returnJsonErrorCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> returnJsonErrorCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#startSkoreSync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> startSkoreSyncAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#checkStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> checkStatusAsync(string accesscode, string serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#changeUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> changeUsernameAsync(string accesscode, string internNumber, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#changeInternNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> changeInternNumberAsync(string accesscode, string username, string newInternNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#changeGroupOwners", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> changeGroupOwnersAsync(string accesscode, string code, string userlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#removeCoAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> removeCoAccountAsync(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#getSchoolyearDataOfClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getSchoolyearDataOfClassAsync(string accesscode, string classCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://bazandpoort.smartschool.be/Webservices/V3#saveSchoolyearDataOfClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveSchoolyearDataOfClassAsync(string accesscode, string classCode, string date, string instituteNumber, string administrativeGroupNumber, string residence, string domain);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface V3PortChannel : SmartschoolWSDL.V3Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class V3PortClient : System.ServiceModel.ClientBase<SmartschoolWSDL.V3Port>, SmartschoolWSDL.V3Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public V3PortClient() : 
                base(V3PortClient.GetDefaultBinding(), V3PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.V3Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public V3PortClient(EndpointConfiguration endpointConfiguration) : 
                base(V3PortClient.GetBindingForEndpoint(endpointConfiguration), V3PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public V3PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(V3PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public V3PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(V3PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public V3PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<object> saveUserAsync(
                    string accesscode, 
                    string internnumber, 
                    string username, 
                    string passwd1, 
                    string passwd2, 
                    string passwd3, 
                    string name, 
                    string surname, 
                    string extranames, 
                    string initials, 
                    string sex, 
                    string birthday, 
                    string birthplace, 
                    string birthcountry, 
                    string address, 
                    string postalcode, 
                    string location, 
                    string country, 
                    string email, 
                    string mobilephone, 
                    string homephone, 
                    string fax, 
                    string prn, 
                    string stamboeknummer, 
                    string basisrol, 
                    string untis)
        {
            return base.Channel.saveUserAsync(accesscode, internnumber, username, passwd1, passwd2, passwd3, name, surname, extranames, initials, sex, birthday, birthplace, birthcountry, address, postalcode, location, country, email, mobilephone, homephone, fax, prn, stamboeknummer, basisrol, untis);
        }
        
        public System.Threading.Tasks.Task<object> saveClassAsync(string accesscode, string name, string desc, string code, string parent, string untis, string instituteNumber, string adminNumber, string schoolYearDate)
        {
            return base.Channel.saveClassAsync(accesscode, name, desc, code, parent, untis, instituteNumber, adminNumber, schoolYearDate);
        }
        
        public System.Threading.Tasks.Task<object> saveGroupAsync(string accesscode, string name, string desc, string code, string parent, string untis)
        {
            return base.Channel.saveGroupAsync(accesscode, name, desc, code, parent, untis);
        }
        
        public System.Threading.Tasks.Task<object> getAllAccountsAsync(string accesscode, string code, string recursive)
        {
            return base.Channel.getAllAccountsAsync(accesscode, code, recursive);
        }
        
        public System.Threading.Tasks.Task<object> getAllAccountsExtendedAsync(string accesscode, string code, string recursive)
        {
            return base.Channel.getAllAccountsExtendedAsync(accesscode, code, recursive);
        }
        
        public System.Threading.Tasks.Task<object> getAllGroupsAndClassesAsync(string accesscode)
        {
            return base.Channel.getAllGroupsAndClassesAsync(accesscode);
        }
        
        public System.Threading.Tasks.Task<string> addCourseAsync(string accesscode, string coursename, string coursedesc, int visibility)
        {
            return base.Channel.addCourseAsync(accesscode, coursename, coursedesc, visibility);
        }
        
        public System.Threading.Tasks.Task<object> addCourseTeacherAsync(string accesscode, string coursename, string coursedesc, string internnummer, string userlist)
        {
            return base.Channel.addCourseTeacherAsync(accesscode, coursename, coursedesc, internnummer, userlist);
        }
        
        public System.Threading.Tasks.Task<object> addCourseStudentsAsync(string accesscode, string coursename, string coursedesc, string groupIds)
        {
            return base.Channel.addCourseStudentsAsync(accesscode, coursename, coursedesc, groupIds);
        }
        
        public System.Threading.Tasks.Task<string> getCoursesAsync(string accesscode)
        {
            return base.Channel.getCoursesAsync(accesscode);
        }
        
        public System.Threading.Tasks.Task<object> delUserAsync(string accesscode, string userIdentifier, string officialDate)
        {
            return base.Channel.delUserAsync(accesscode, userIdentifier, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> saveUserParameterAsync(string accesscode, string userIdentifier, string paramName, string paramValue)
        {
            return base.Channel.saveUserParameterAsync(accesscode, userIdentifier, paramName, paramValue);
        }
        
        public System.Threading.Tasks.Task<string> getClassListAsync(object accesscode)
        {
            return base.Channel.getClassListAsync(accesscode);
        }
        
        public System.Threading.Tasks.Task<string> getClassListJsonAsync(object accesscode)
        {
            return base.Channel.getClassListJsonAsync(accesscode);
        }
        
        public System.Threading.Tasks.Task<object> saveClassListAsync(string accesscode, string serializedList)
        {
            return base.Channel.saveClassListAsync(accesscode, serializedList);
        }
        
        public System.Threading.Tasks.Task<object> saveClassListJsonAsync(string accesscode, string jsonList)
        {
            return base.Channel.saveClassListJsonAsync(accesscode, jsonList);
        }
        
        public System.Threading.Tasks.Task<object> delClassAsync(string accesscode, string code)
        {
            return base.Channel.delClassAsync(accesscode, code);
        }
        
        public System.Threading.Tasks.Task<object> saveUserToClassesAsync(string accesscode, string userIdentifier, string csvList)
        {
            return base.Channel.saveUserToClassesAsync(accesscode, userIdentifier, csvList);
        }
        
        public System.Threading.Tasks.Task<object> removeUserFromGroupAsync(string accesscode, string userIdentifier, string @class, string officialDate)
        {
            return base.Channel.removeUserFromGroupAsync(accesscode, userIdentifier, @class, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> clearGroupAsync(string accesscode, string group, string officialDate)
        {
            return base.Channel.clearGroupAsync(accesscode, group, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> saveUserToClassAsync(string accesscode, string userIdentifier, string @class, string officialDate)
        {
            return base.Channel.saveUserToClassAsync(accesscode, userIdentifier, @class, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> saveUserToClassesAndGroupsAsync(string accesscode, string userIdentifier, string csvList, int keepOld)
        {
            return base.Channel.saveUserToClassesAndGroupsAsync(accesscode, userIdentifier, csvList, keepOld);
        }
        
        public System.Threading.Tasks.Task<object> setAccountStatusAsync(string accesscode, string userIdentifier, object accountStatus)
        {
            return base.Channel.setAccountStatusAsync(accesscode, userIdentifier, accountStatus);
        }
        
        public System.Threading.Tasks.Task<object> setAccountPhotoAsync(string accesscode, string userIdentifier, string photo)
        {
            return base.Channel.setAccountPhotoAsync(accesscode, userIdentifier, photo);
        }
        
        public System.Threading.Tasks.Task<string> getAccountPhotoAsync(string accesscode, string userIdentifier)
        {
            return base.Channel.getAccountPhotoAsync(accesscode, userIdentifier);
        }
        
        public System.Threading.Tasks.Task<object> replaceInumAsync(string accesscode, string oldInum, string newInum)
        {
            return base.Channel.replaceInumAsync(accesscode, oldInum, newInum);
        }
        
        public System.Threading.Tasks.Task<object> forcePasswordResetAsync(string accesscode, string userIdentifier, int accountType)
        {
            return base.Channel.forcePasswordResetAsync(accesscode, userIdentifier, accountType);
        }
        
        public System.Threading.Tasks.Task<object> savePasswordAsync(string accesscode, string userIdentifier, string password, int accountType)
        {
            return base.Channel.savePasswordAsync(accesscode, userIdentifier, password, accountType);
        }
        
        public System.Threading.Tasks.Task<object> sendMsgAsync(string accesscode, string userIdentifier, string title, string body, string senderIdentifier, object attachments, int coaccount, bool copyToLVS)
        {
            return base.Channel.sendMsgAsync(accesscode, userIdentifier, title, body, senderIdentifier, attachments, coaccount, copyToLVS);
        }
        
        public System.Threading.Tasks.Task<object> getSkoreClassTeacherCourseRelationAsync(string accesscode)
        {
            return base.Channel.getSkoreClassTeacherCourseRelationAsync(accesscode);
        }
        
        public System.Threading.Tasks.Task<object> unregisterStudentAsync(string accesscode, string userIdentifier, string officialDate)
        {
            return base.Channel.unregisterStudentAsync(accesscode, userIdentifier, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> getClassTeachersAsync(string accesscode, bool getAllOwners)
        {
            return base.Channel.getClassTeachersAsync(accesscode, getAllOwners);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsByDateAsync(string accesscode, string date)
        {
            return base.Channel.getAbsentsByDateAsync(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsWithInternalNumberByDateAsync(string accesscode, string date)
        {
            return base.Channel.getAbsentsWithInternalNumberByDateAsync(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsWithUsernameByDateAsync(string accesscode, string date)
        {
            return base.Channel.getAbsentsWithUsernameByDateAsync(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsByDateAndGroupAsync(string accesscode, string date, string code)
        {
            return base.Channel.getAbsentsByDateAndGroupAsync(accesscode, date, code);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsWithAliasByDateAsync(string accesscode, string date)
        {
            return base.Channel.getAbsentsWithAliasByDateAsync(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsAsync(string accesscode, string userIdentifier, string schoolYear)
        {
            return base.Channel.getAbsentsAsync(accesscode, userIdentifier, schoolYear);
        }
        
        public System.Threading.Tasks.Task<string> getUserDetailsAsync(string accesscode, string userIdentifier)
        {
            return base.Channel.getUserDetailsAsync(accesscode, userIdentifier);
        }
        
        public System.Threading.Tasks.Task<string> getUserDetailsByNumberAsync(string accesscode, string number)
        {
            return base.Channel.getUserDetailsByNumberAsync(accesscode, number);
        }
        
        public System.Threading.Tasks.Task<string> getUserDetailsByUsernameAsync(string accesscode, string username)
        {
            return base.Channel.getUserDetailsByUsernameAsync(accesscode, username);
        }
        
        public System.Threading.Tasks.Task<string> getUserOfficialClassAsync(string accesscode, string userIdentifier, string date)
        {
            return base.Channel.getUserOfficialClassAsync(accesscode, userIdentifier, date);
        }
        
        public System.Threading.Tasks.Task<bool> saveSignatureAsync(string accesscode, string userIdentifier, int accountType, string signature)
        {
            return base.Channel.saveSignatureAsync(accesscode, userIdentifier, accountType, signature);
        }
        
        public System.Threading.Tasks.Task<string> getStudentCareerAsync(string accesscode, string userIdentifier)
        {
            return base.Channel.getStudentCareerAsync(accesscode, userIdentifier);
        }
        
        public System.Threading.Tasks.Task<object> deactivateTwoFactorAuthenticationAsync(string accesscode, string userIdentifier, int accountType)
        {
            return base.Channel.deactivateTwoFactorAuthenticationAsync(accesscode, userIdentifier, accountType);
        }
        
        public System.Threading.Tasks.Task returnErrorCodesAsync()
        {
            return base.Channel.returnErrorCodesAsync();
        }
        
        public System.Threading.Tasks.Task<string> returnCsvErrorCodesAsync()
        {
            return base.Channel.returnCsvErrorCodesAsync();
        }
        
        public System.Threading.Tasks.Task<string> returnJsonErrorCodesAsync()
        {
            return base.Channel.returnJsonErrorCodesAsync();
        }
        
        public System.Threading.Tasks.Task<string> startSkoreSyncAsync(string accesscode)
        {
            return base.Channel.startSkoreSyncAsync(accesscode);
        }
        
        public System.Threading.Tasks.Task<string> checkStatusAsync(string accesscode, string serviceId)
        {
            return base.Channel.checkStatusAsync(accesscode, serviceId);
        }
        
        public System.Threading.Tasks.Task<int> changeUsernameAsync(string accesscode, string internNumber, string newUsername)
        {
            return base.Channel.changeUsernameAsync(accesscode, internNumber, newUsername);
        }
        
        public System.Threading.Tasks.Task<int> changeInternNumberAsync(string accesscode, string username, string newInternNumber)
        {
            return base.Channel.changeInternNumberAsync(accesscode, username, newInternNumber);
        }
        
        public System.Threading.Tasks.Task<int> changeGroupOwnersAsync(string accesscode, string code, string userlist)
        {
            return base.Channel.changeGroupOwnersAsync(accesscode, code, userlist);
        }
        
        public System.Threading.Tasks.Task<object> removeCoAccountAsync(string accesscode, string userIdentifier, int accountType)
        {
            return base.Channel.removeCoAccountAsync(accesscode, userIdentifier, accountType);
        }
        
        public System.Threading.Tasks.Task<object> getSchoolyearDataOfClassAsync(string accesscode, string classCode)
        {
            return base.Channel.getSchoolyearDataOfClassAsync(accesscode, classCode);
        }
        
        public System.Threading.Tasks.Task<object> saveSchoolyearDataOfClassAsync(string accesscode, string classCode, string date, string instituteNumber, string administrativeGroupNumber, string residence, string domain)
        {
            return base.Channel.saveSchoolyearDataOfClassAsync(accesscode, classCode, date, instituteNumber, administrativeGroupNumber, residence, domain);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.V3Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.V3Port))
            {
                return new System.ServiceModel.EndpointAddress("https://bazandpoort.smartschool.be/Webservices/V3");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return V3PortClient.GetBindingForEndpoint(EndpointConfiguration.V3Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return V3PortClient.GetEndpointAddress(EndpointConfiguration.V3Port);
        }
        
        public enum EndpointConfiguration
        {
            
            V3Port,
        }
    }
}
